# Generated by Django 4.2.4 on 2023-09-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example__simple_admin', '0004_alter_productmodel_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='main_image',
            field=models.CharField(max_length=100),
        ),
    ]
