# Generated by Django 3.2.19 on 2023-09-27 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example__simple_admin', '0004_alter_productmodel_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='slug',
        ),
    ]
