# Generated by Django 3.2.20 on 2023-09-29 04:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example__simple_admin', '0006_productmodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='code')),
                ('value', models.CharField(help_text='in percentage', max_length=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='count of the discount')),
            ],
            options={
                'verbose_name': 'discount',
                'verbose_name_plural': 'Discounts',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_delivery', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True)),
                ('notice', models.TextField(blank=True)),
                ('date_of_order', models.DateTimeField(auto_now_add=True)),
                ('date_of_send', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New Order'), ('APR', 'Approved'), ('PAY', 'Payed'), ('CNL', 'Canceled')], default='NEW', max_length=3)),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='example__simple_admin.discountmodel')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-date_of_order'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('count', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_line_order', to='example__simple_admin.ordermodel')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_line_product', to='example__simple_admin.productmodel')),
            ],
            options={
                'verbose_name': 'order line',
                'verbose_name_plural': 'Order lines',
            },
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='example__simple_admin.productcategory'),
        ),
    ]
