# Generated by Django 3.2.20 on 2023-09-29 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example__simple_admin', '0007_auto_20230929_0759'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='ProductCategoryModel',
        ),
    ]
