# Generated by Django 3.2.20 on 2023-09-29 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example__simple_admin', '0008_rename_productcategory_productcategorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='example__simple_admin.productcategorymodel'),
            preserve_default=False,
        ),
    ]
