# Generated by Django 3.2.20 on 2023-09-30 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example__simple_admin', '0009_alter_productmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='count',
        ),
    ]
